=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/events/login_events.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="login_events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="login_event" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                        <xs:attribute name="active" type="xs:int" use="required"/>
                        <xs:attribute name="period_start" type="xs:dateTime" use="required"/>
                        <xs:attribute name="period_end" type="xs:dateTime" use="required"/>
                        <xs:attribute name="attend_type" type="AttendType" use="required"/>
                        <xs:attribute name="attend_num" type="xs:int"/>
                        <xs:attribute name="reward_item" type="xs:int" use="required"/>
                        <xs:attribute name="reward_item_num" type="xs:int" use="required"/>
                        <xs:attribute name="reward_item_expire" type="xs:int"/>
						<xs:attribute name="reward_item_expire_time" type="xs:int"/>
						<xs:attribute name="reward_permit_level" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="AttendType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAILY"/>
            <xs:enumeration value="ANNIVERSARY"/>
            <xs:enumeration value="CUMULATIVE"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/events/login_events.xml
<?xml version='1.0' encoding='UTF-8'?>
<login_events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="login_events.xsd">
	<login_event id="1" active="1" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="188052315" reward_item_num="1" reward_item_expire_time="1440"/>
	<login_event id="2" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="5" reward_item="165010001" reward_item_num="1"/>
	<login_event id="3" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="10" reward_item="166000120" reward_item_num="1"/>
	<login_event id="4" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="15" reward_item="166030005" reward_item_num="1" reward_item_expire_time="10"/>
	<login_event id="5" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="20" reward_item="168000118" reward_item_num="1"/>
	<login_event id="6" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="30" reward_permit_level="50" reward_item="169220032" reward_item_num="1"/>
	<login_event id="7" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="4" reward_permit_level="46" reward_item="188052830" reward_item_num="1"/>
	<login_event id="8" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="5" reward_item="188052831" reward_item_num="1"/>
	<login_event id="9" active="1" period_start="2014-03-15T00:00:00" period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="166000010" reward_item_num="1"/>
	<login_event id="10" active="0" period_start="2014-03-15T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="10" reward_item="166000030" reward_item_num="1"/>
	<login_event id="11" active="0" period_start="2014-03-15T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="20" reward_item="166000040" reward_item_num="1"/>
	<login_event id="12" active="0" period_start="2014-03-15T00:00:00" period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="166000050" reward_item_num="1"/>
	<login_event id="13" active="0" period_start="2014-03-15T00:00:00" period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="5" reward_item="166000060" reward_item_num="1"/>
	<login_event id="14" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="1" reward_permit_level="46" reward_item="188053423" reward_item_num="1"/>
	<login_event id="15" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="2" reward_permit_level="46" reward_item="188053424" reward_item_num="1"/>
	<login_event id="16" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="3" reward_permit_level="46" reward_item="188053425" reward_item_num="1"/>
	<login_event id="17" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="4" reward_permit_level="46" reward_item="188053426" reward_item_num="1"/>
	<login_event id="18" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="5" reward_permit_level="46" reward_item="188053427" reward_item_num="1"/>
	<login_event id="19" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="6" reward_permit_level="46" reward_item="188053428" reward_item_num="1"/>
	<login_event id="20" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="7" reward_permit_level="46" reward_item="188053429" reward_item_num="1"/>
	<login_event id="21" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="8" reward_permit_level="46" reward_item="188053430" reward_item_num="1"/>
	<login_event id="22" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="9" reward_permit_level="46" reward_item="188053431" reward_item_num="1"/>
	<login_event id="23" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="10" reward_permit_level="46" reward_item="188053432" reward_item_num="1"/>
	<login_event id="24" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="11" reward_permit_level="46" reward_item="188053433" reward_item_num="1"/>
	<login_event id="25" active="1" period_start="2014-04-01T09:00:00" period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="12" reward_permit_level="46" reward_item="188053434" reward_item_num="1"/>
	<login_event id="26" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="1" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="27" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="2" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="28" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="3" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="29" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="4" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="30" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="5" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="31" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="6" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="32" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="7" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="33" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="8" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="34" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="9" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="35" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="10" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="36" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="11" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="37" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="12" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="38" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="1" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="39" active="0" period_start="2014-03-01T00:00:00" period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="2" reward_permit_level="46" reward_item="166000050" reward_item_num="1"/>
	<login_event id="40" active="1" period_start="2014-04-01T09:00:00" period_end="2014-05-01T08:59:59" attend_type="CUMULATIVE" attend_num="7" reward_item="188053416" reward_item_num="1"/>
	<login_event id="41" active="1" period_start="2014-04-01T09:00:00" period_end="2014-05-01T08:59:59" attend_type="CUMULATIVE" attend_num="14" reward_item="186000247" reward_item_num="1"/>
	<login_event id="42" active="1" period_start="2014-04-01T09:00:00" period_end="2014-05-01T08:59:59" attend_type="CUMULATIVE" attend_num="21" reward_item="188053417" reward_item_num="1"/>
	<login_event id="43" active="1" period_start="2014-04-01T09:00:00" period_end="2014-05-01T08:59:59" attend_type="CUMULATIVE" attend_num="28" reward_permit_level="46" reward_item="166030008" reward_item_num="1" reward_item_expire_time="10080"/>
	<login_event id="44" active="1" period_start="2014-04-01T09:00:00" period_end="2014-06-01T08:59:59" attend_type="DAILY" attend_num="1" reward_item="188053409" reward_item_num="1"/>
	<login_event id="45" active="1" period_start="2014-06-01T09:00:00" period_end="2014-09-01T08:59:59" attend_type="DAILY" attend_num="1" reward_item="188053410" reward_item_num="1"/>
	<login_event id="46" active="1" period_start="2014-09-01T09:00:00" period_end="2014-12-01T08:59:59" attend_type="DAILY" attend_num="1" reward_item="188053411" reward_item_num="1"/>
	<login_event id="47" active="1" period_start="2014-12-01T09:00:00" period_end="2015-03-01T08:59:59" attend_type="DAILY" attend_num="1" reward_item="188053412" reward_item_num="1"/>
	<login_event id="48" active="1" period_start="2014-05-01T09:00:00" period_end="2014-06-01T08:59:59" attend_type="CUMULATIVE" attend_num="7" reward_item="188053416" reward_item_num="1"/>
