=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/npc_skills/npc_skills.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:element name="npc_skill_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="npc_skills" type="NpcSkillList" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NpcSkillList">
		<xs:sequence>
			<xs:element name="npc_skill" type="NpcSkillTemplate" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="npc_ids" type="IntListType" />
	</xs:complexType>
	<xs:complexType name="NpcSkillTemplate">
		<xs:sequence>
			<xs:element name="cond" type="NpcSkillConditionTemplate" minOccurs="0" />
			<xs:element name="spawn_npc" type="NpcSkillSpawn" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="lv" type="xs:int" />
		<xs:attribute name="prob" type="xs:int" />
		<xs:attribute name="max_hp" type="xs:int" default="100" />
		<xs:attribute name="min_hp" type="xs:int" />
		<xs:attribute name="max_time" type="xs:int" />
		<xs:attribute name="min_time" type="xs:int" />
		<xs:attribute name="conjunction" type="ConjunctionType" />
		<xs:attribute name="cd" type="xs:int" />
		<xs:attribute name="is_post_spawn" type="xs:boolean" />
		<xs:attribute name="prio" type="xs:int" />
		<xs:attribute name="next_skill_time" type="xs:int" />
		<xs:attribute name="next_chain_id" type="xs:int" />
		<xs:attribute name="chain_id" type="xs:int" />
		<xs:attribute name="max_chain_time" type="xs:int" />
		<xs:attribute name="target" type="NpcSkillTargetAttribute" />
	</xs:complexType>
	<xs:complexType name="NpcSkillConditionTemplate">
		<xs:attribute name="cond_type" type="ConditionType" />
		<xs:attribute name="range" type="xs:int" />
		<xs:attribute name="hp_below" type="xs:int" />
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="despawn_time" type="xs:int" />
		<xs:attribute name="can_die" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="NpcSkillSpawn">
		<xs:attribute name="npc_id" type="xs:int" />
		<xs:attribute name="delay" type="xs:int" />
		<xs:attribute name="min_distance" type="xs:int" />
		<xs:attribute name="max_distance" type="xs:int" />
		<xs:attribute name="min_count" type="xs:int" default="1" />
		<xs:attribute name="max_count" type="xs:int" />
	</xs:complexType>
	<xs:simpleType name="ConjunctionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AND" />
			<xs:enumeration value="OR" />
			<xs:enumeration value="XOR" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConditionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="HELP_FRIEND" />
			<xs:enumeration value="TARGET_IS_IN_ANY_STUN" />
			<xs:enumeration value="TARGET_IS_IN_RANGE" />
			<xs:enumeration value="TARGET_IS_IN_STUMBLE" />
			<xs:enumeration value="TARGET_IS_STUNNED" />
			<xs:enumeration value="TARGET_IS_SLEEPING" />
			<xs:enumeration value="TARGET_IS_AETHERS_HOLD" />
			<xs:enumeration value="TARGET_IS_POISONED" />
			<xs:enumeration value="TARGET_IS_BLEEDING" />
			<xs:enumeration value="TARGET_IS_FLYING" />
			<xs:enumeration value="TARGET_IS_GATE" />
			<xs:enumeration value="TARGET_IS_PLAYER" />
			<xs:enumeration value="TARGET_IS_NPC" />
			<xs:enumeration value="TARGET_IS_PHYSICAL_CLASS" />
			<xs:enumeration value="TARGET_IS_MAGICAL_CLASS" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_II" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_III" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_IV" />
			<xs:enumeration value="TARGET_HAS_CARVED_SIGNET_LEVEL_V" />
			<xs:enumeration value="NPC_IS_ALIVE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NpcSkillTargetAttribute">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FRIEND" />
			<xs:enumeration value="ME" />
			<xs:enumeration value="MOST_HATED" />
			<xs:enumeration value="SECOND_MOST_HATED" />
			<xs:enumeration value="THIRD_MOST_HATED" />
			<xs:enumeration value="RANDOM" />
			<xs:enumeration value="RANDOM_EXCEPT_CURRENT_TARGET" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/npc_skills/instances/300800000_Infinity_Shard.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Hyperion -->
	<npc_skills npc_ids="231073">
		<npc_skill id="21254" is_post_spawn="true" />
		<npc_skill id="21241" lv="56" prob="65" target="RANDOM_EXCEPT_CURRENT_TARGET" cd="120000"/>
		<npc_skill id="21241" lv="56" prob="65" cd="30000"/>
		<npc_skill id="21242" lv="56" prob="70" cd="8000" />
		<npc_skill id="21243" lv="56" prob="70" cd="8000" />
		<npc_skill id="21244" lv="56" prob="60" max_hp="80" cd="35000" />
		<npc_skill id="21245" lv="56" prob="60" min_hp="15" max_hp="75" cd="25000"/>
		<npc_skill id="21247" lv="56" prob="60" min_hp="50" max_hp="80" cd="30000"/>
		<npc_skill id="21247" lv="56" prob="50" min_hp="50" max_hp="80" cd="140000" target="RANDOM_EXCEPT_CURRENT_TARGET" />
		<npc_skill id="21248" lv="56" prob="50" min_hp="15" max_hp="45" cd="140000" target="RANDOM_EXCEPT_CURRENT_TARGET" />
		<npc_skill id="21248" lv="56" prob="60" min_hp="15" max_hp="45" cd="30000" />
		<npc_skill id="21249" lv="56" prob="50" max_hp="10" cd="140000" target="RANDOM_EXCEPT_CURRENT_TARGET"/>
		<npc_skill id="21249" lv="56" prob="60" max_hp="10" cd="30000"/>
		<npc_skill id="21250" lv="56" prob="70" min_hp="30" max_hp="75" chain_id="0" next_chain_id="1" next_skill_time="0" cd="55000" prio="2"/>
		<npc_skill id="21251" lv="56" prob="100" chain_id="1" />
		<npc_skill id="21250" lv="56" prob="70" max_hp="25" chain_id="0" next_chain_id="4" next_skill_time="0" cd="55000" prio="1"/>
		<npc_skill id="21252" lv="56" prob="100" chain_id="4"/>
	</npc_skills>
	<!-- Ide Forcefield Generator -->
	<npc_skills npc_ids="231074 231078 231082 231086">
		<npc_skill id="21371" lv="41" is_post_spawn="true" />
	</npc_skills>
	<!-- Agent Kabalash -->
	<npc_skills npc_ids="231075 231087">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="20701" lv="56" is_post_spawn="true"/>
		<npc_skill id="20712" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17722" lv="56" prob="70" cd="10000"/>
		<npc_skill id="17335" lv="56" prob="70" cd="10000"/>
		<npc_skill id="20179" lv="10" prob="70" cd="15000"/> <!-- TODO change to lv="56" when new NpcStats and damage calculations are implemented -->
		<npc_skill id="21288" lv="56" prob="70" cd="10000"/>
		<npc_skill id="20711" lv="56" prob="70" cd="10000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Sniper -->
	<npc_skills npc_ids="231076 231077 231080 231088">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17106" lv="56" prob="70" cd="20000"/>
		<npc_skill id="17318" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17317" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17314" lv="56" prob="70" cd="12000"/>
		<npc_skill id="21230" lv="56" prob="60"	cd="15000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Gunner -->
	<npc_skills npc_ids="231091">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="21292" lv="56" prob="80" cd="8000"/>
		<npc_skill id="21293" lv="56" prob="70" cd="15000"/>
	</npc_skills>
	<!-- Hyperion Defense Turret -->
	<npc_skills npc_ids="231102">
		<npc_skill id="16896" lv="56" prob="70" cd="15000" />
		<npc_skill id="17003" lv="56" prob="70" cd="15000" />
		<npc_skill id="21415" lv="56" prob="70" cd="15000" />
	</npc_skills>
	<!-- Ide Pool -->
	<npc_skills npc_ids="231104">
		<npc_skill id="21356" lv="56" prob="20" />
	</npc_skills>
	<!-- summoned ancient tyrhund -->
	<npc_skills npc_ids="231103">
		<npc_skill id="21300" lv="56" prob="80" cd="15000"/>
		<npc_skill id="20947" lv="56" prob="20" cd="25000"/>
	</npc_skills>
	<!-- hyperion defense combatant -->
	<npc_skills npc_ids="231096 231099 231084">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17294" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21284" lv="56" prob="70" cd="12000"/>
	</npc_skills>
	<!-- hyperion defense scout -->
	<npc_skills npc_ids="231097 231100">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17322" lv="56" prob="70" cd="12000" next_chain_id="1" next_skill_time="0"/>
		<npc_skill id="16678" lv="56" prob="100" cd="8000" chain_id="1"/>
		<npc_skill id="17295" lv="56" prob="70" cd="8000"/>
	</npc_skills>
	<!-- hyperion defense medic -->
	<npc_skills npc_ids="231098 231101">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17359" lv="56" prob="70" cd="7000"/>
		<npc_skill id="17360" lv="56" prob="70" cd="12000"/>
		<npc_skill id="17361" lv="56" prob="100" max_hp="60" cd="15000" prio="1"/>
	</npc_skills>
	<!-- hyperion defense elite sniper -->
	<npc_skills npc_ids="231089">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17318" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17106" lv="56" prob="60" cd="20000"/>
		<npc_skill id="17317" lv="56" prob="70" cd="8000"/>
		<npc_skill id="17314" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21230" lv="56" prob="70" cd="9000"/>
	</npc_skills>
	<!-- Hyperion Defense Elite Assassin -->
	<npc_skills npc_ids="231079 231083">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17321" lv="56" prob="80" cd="8000" chain_id="1"/>
		<npc_skill id="17332" lv="56" cd="8000" />
		<npc_skill id="21289" lv="56" prob="80" cd="10000"/>
		<npc_skill id="16452" lv="56" prob="100" cd="30000" next_chain_id="1" next_skill_time="0"/>
	</npc_skills>
	<!-- hyperion defense elite fighter -->
	<npc_skills npc_ids="231090">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17295" lv="56" prob="80" cd="10000"/>
		<npc_skill id="17294" lv="56" prob="80" cd="6000"/>
	</npc_skills>
	<!-- hyperion defense elite medic -->
	<npc_skills npc_ids="231081 231085">
		<npc_skill id="20700" lv="56" is_post_spawn="true"/>
		<npc_skill id="17359" lv="56" prob="70" cd="8000"/>
		<npc_skill id="21278" lv="56" prob="70" cd="15000"/>
		<npc_skill id="17361" lv="56" prob="100" cd="15000" max_hp="60" prio="1"/>
		<npc_skill id="17700" lv="56" prob="70" cd="15000"/>
		<npc_skill id="16566" lv="56" prob="100" cd="10000" max_hp="80" prio="1"/>
	</npc_skills>
</npc_skill_templates>

=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/npc_skills/instances/301110000_Danuar_Reliquary.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<!-- Cursed Queen Modor -->
	<npc_skills npc_ids="231304">
		<npc_skill id="21174" lv="1" prob="70" cd="10000" next_skill_time="6000"/><!-- Freezing Sphere of Malice -->
		<npc_skill id="21175" lv="1" prob="70" cd="10000" next_skill_time="6000"/><!-- Freezing Sphere of Revenge -->
	</npc_skills>
	<!-- Enraged Queen Modor -->
	<npc_skills npc_ids="231305">
		<npc_skill id="21181" lv="1" prob="0" is_post_spawn="true"/> <!-- Malevolence -->
		<npc_skill id="21742" lv="1" prob="70" cd="10000" next_skill_time="6000"/><!-- Subzero Malice -->
		<npc_skill id="21743" lv="1" prob="70" cd="10000" next_skill_time="6000"/><!-- Rushing Subzero Malice -->
	</npc_skills>
	<!-- Modor's Clone -->
	<npc_skills npc_ids="284383">
		<npc_skill id="21181" lv="1" prob="0" is_post_spawn="true"/> <!-- Malevolence -->
		<npc_skill id="21372" lv="1" prob="100" cd="20000" next_skill_time="8000" max_chain_time="15000" next_chain_id="1"/> <!-- Freezing Sphere of Malice -->
		<npc_skill id="21373" lv="1" prob="100" cd="20000" next_skill_time="9000" max_chain_time="15000" chain_id="1" next_chain_id="2"/> <!-- Freezing Sphere of Revenge -->
		<npc_skill id="21372" lv="1" prob="100" cd="20000" next_skill_time="8000" max_chain_time="15000" chain_id="2" next_chain_id="3"/> <!-- Freezing Sphere of Malice -->
		<npc_skill id="21373" lv="1" prob="100" cd="20000" next_skill_time="10000" max_chain_time="17000" chain_id="3" next_chain_id="4"/> <!-- Freezing Sphere of Revenge -->
		<npc_skill id="21177" lv="1" prob="100" cd="20000" next_skill_time="15000" chain_id="4" /> <!-- Vengeful Orb -->
	</npc_skills>
	<!-- danuar reliquary novun -->
	<npc_skills npc_ids="284377 284659 856493">
		<npc_skill id="17029" lv="1" prob="60" cd="25000" is_post_spawn="true"/>
		<npc_skill id="16516" lv="1" prob="70" cd="22000"/>
		<npc_skill id="17949" lv="1" prob="70" cd="22000"/>
	</npc_skills>
	<!-- idean lapilima -->
	<npc_skills npc_ids="284378 284660 856494">
		<npc_skill id="16540" lv="1" prob="70" cd="22000"/>
		<npc_skill id="16984" lv="1" prob="70" cd="22000"/>
	</npc_skills>
	<!-- idean obscura -->
	<npc_skills npc_ids="284379 284661 856495">
		<npc_skill id="16540" lv="1" prob="65" cd="23000"/>
		<npc_skill id="16762" lv="1" prob="65" cd="23000"/>
		<npc_skill id="16984" lv="1" prob="65" cd="23000"/>
	</npc_skills>
	<!-- modor's bodyguard -->
	<npc_skills npc_ids="284380 284662 856496">
		<npc_skill id="21265" lv="1" prob="60" cd="25000" is_post_spawn="true"/>
		<npc_skill id="16516" lv="1" prob="70" cd="22000"/>
		<npc_skill id="16984" lv="1" prob="70" cd="22000"/>
	</npc_skills>
	<!-- vengeful reaper -->
	<npc_skills npc_ids="284381 284663 856497">
		<npc_skill id="16516" lv="1" prob="70" cd="22000"/>
		<npc_skill id="16984" lv="1" prob="70" cd="22000"/>
	</npc_skills>
	<!-- hoarfrost acheron drake -->
	<npc_skills npc_ids="284382 284664 856498">
		<npc_skill id="17531" lv="1" prob="65" cd="23000"/>
		<npc_skill id="16577" lv="1" prob="65" cd="23000"/>
		<npc_skill id="21267" lv="1" prob="65" cd="23000"/>
	</npc_skills>
</npc_skill_templates>

=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/npc_skills/rift_guard_skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_skills.xsd">
	<!-- Chaos Guardian Generals -->
	<npc_skills npc_ids="219887 219906 219913 236035 236048 236055">
		<npc_skill id="21750" lv="65" prob="90" min_hp="35" cd="15000" /> <!-- Slash -->
		<npc_skill id="21752" lv="1" prob="70" cd="80000" next_skill_time="5000" min_hp="0" max_hp="75" /> <!-- Searing Scream -->
		<npc_skill id="21753" lv="65" prob="85" max_hp="34" cd="15000" /> <!-- Flying Blade -->
		<npc_skill id="21756" lv="65" prob="90" next_chain_id="1" next_skill_time="0" cd="90000" min_hp="0" max_hp="45" target="RANDOM_EXCEPT_CURRENT_TARGET" /> <!-- Prime Target -->
		<npc_skill id="21757" lv="65" prob="100" chain_id="1" cd="20000" next_skill_time="5000" /> <!-- Punishing Blow -->
		<npc_skill id="21758" lv="1" prob="70" cd="85000" next_skill_time="3000" target="NONE" /> <!-- Fetters -->
		<npc_skill id="17992" lv="1" prob="30" next_chain_id="2" next_skill_time="0" cd="120000" min_hp="0" max_hp="45" /> <!-- Wide Area Aerial Thrust III -->
		<npc_skill id="17995" lv="1" prob="100" chain_id="2" next_skill_time="8000" cd="20000" target="NONE"> <!-- Wide Area Crashing Wind Strike III -->
			<cond cond_type="TARGET_IS_AETHERS_HOLD" />
		</npc_skill>
	</npc_skills>
</npc_skill_templates>

=== hanmahong5-arch/BEY_4.8/server/source/game-server/data/static_data/npc_skills/instances/300700000_The_Hexway.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../npc_skills.xsd">
	<npc_skills npc_ids="219600"><!-- Laksyaka Legatus -->
		<npc_skill id="18166" lv="50" prob="18" />
		<npc_skill id="16785" lv="50" prob="36" />
		<npc_skill id="18164" lv="50" prob="9" />
		<npc_skill id="16608" lv="50" prob="9" />
		<npc_skill id="16519" lv="50" prob="27" />
	</npc_skills>
	<npc_skills npc_ids="219601"><!-- Laksyaka Magus -->
		<npc_skill id="18174" lv="50" prob="36" />
		<npc_skill id="17039" lv="50" prob="18" />
		<npc_skill id="16775" lv="50" prob="27" />
		<npc_skill id="18157" lv="50" prob="9" />
		<npc_skill id="18175" lv="50" prob="9" />
	</npc_skills>
	<npc_skills npc_ids="219602"><!-- Laksyaka Ambusher -->
		<npc_skill id="16608" lv="50" prob="18" />
		<npc_skill id="16540" lv="50" prob="18" />
		<npc_skill id="17934" lv="50" prob="18" />
		<npc_skill id="18159" lv="50" prob="29" />
		<npc_skill id="18158" lv="50" prob="12" />
		<npc_skill id="19125" lv="50" prob="6" />
	</npc_skills>
	<npc_skills npc_ids="219603"><!-- Laksyaka Sniper -->
		<npc_skill id="18173" lv="50" prob="25" />
		<npc_skill id="17003" lv="50" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219604"><!-- Laksyaka Officer -->
		<npc_skill id="17008" lv="50" prob="21" />
		<npc_skill id="16566" lv="50" prob="25" />
		<npc_skill id="16563" lv="50" prob="24" />
		<npc_skill id="16638" lv="50" prob="14" />
		<npc_skill id="16565" lv="50" prob="4" />
		<npc_skill id="16837" lv="50" prob="4" />
	</npc_skills>
	<npc_skills npc_ids="219605"><!-- Laksyaka Infantry -->
		<npc_skill id="17475" lv="54" prob="25" />
		<npc_skill id="17465" lv="54" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219606"><!-- Laksyaka Bladesworn -->
		<npc_skill id="17420" lv="54" prob="25" />
		<npc_skill id="17408" lv="54" prob="25" />
	</npc_skills>
	<npc_skills npc_ids="219607"><!-- Laksyaka Sentry -->
		<npc_skill id="17492" lv="54" prob="33" />
		<npc_skill id="17489" lv="54" prob="50" />
		<npc_skill id="17490" lv="54" prob="17" />
	</npc_skills>
	<npc_skills npc_ids="219608"><!-- Laksyaka Elite Medic -->
		<npc_skill id="17480" lv="54" prob="29" />
		<npc_skill id="16635" lv="54" prob="14" />
		<npc_skill id="17487" lv="54" prob="21" />
		<npc_skill id="17486" lv="54" prob="14" />
		<npc_skill id="16563" lv="54" prob="7" />
		<npc_skill id="17497" lv="54" prob="7" />
		<npc_skill id="17485" lv="54" prob="7" />
	</npc_skills>
	<npc_skills npc_ids="219609"><!-- Captain Jarka -->
		<npc_skill id="18166" lv="54" prob="29" />
		<npc_skill id="16608" lv="54" prob="29" />
		<npc_skill id="16519" lv="54" prob="29" />
		<npc_skill id="18165" lv="54" prob="14" />
	</npc_skills>
	<npc_skills npc_ids="286933 219610"><!-- Captain Lakhara (B3), Adjutant Galamat (B5) -->
		<npc_skill id="16608" lv="65" prob="75" cd="15000" />
		<npc_skill id="17497" lv="65" prob="75" cd="20000" />
		<npc_skill id="17485" lv="65" prob="50" cd="35000" />
		<npc_skill id="17039" lv="65" prob="30" cd="5000" next_skill_time="3000" target="RANDOM_EXCEPT_CURRENT_TARGET" />
		<npc_skill id="17480" lv="65" prob="60" cd="30000" target="RANDOM" />
	</npc_skills>
	<npc_skills npc_ids="219611 219614"><!-- Laksyaka Bladesworn (B1), Laksyaka Infantry (B6) -->
		<npc_skill id="17480" lv="65" prob="75" cd="6000" target="RANDOM_EXCEPT_CURRENT_TARGET" />
		<npc_skill id="17497" lv="65" prob="75" cd="15000" />
		<npc_skill id="18164" lv="65" prob="75" cd="10000" target="MOST_HATED" />
		<npc_skill id="18174" lv="65" prob="100" cd="20000" max_time="50000" min_time="30000" />
	</npc_skills>
	<npc_skills npc_ids="219612 219613"><!-- Laksyaka Infantry (B3), Laksyaka Infantry(B4) -->
		<npc_skill id="17480" lv="65" prob="75" cd="6000" target="RANDOM_EXCEPT_CURRENT_TARGET" />
		<npc_skill id="17497" lv="65" prob="75" cd="15000" />
		<npc_skill id="18164" lv="65" prob="75" cd="10000" target="MOST_HATED" />
		<npc_skill id="18174" lv="65" prob="100" cd="20000" max_time="50000" min_time="30000" />
	</npc_skills>
	<npc_skills npc_ids="219634"><!-- Laksyaka Legatus -->
		<npc_skill id="18166" lv="50" prob="30" />
		<npc_skill id="16785" lv="50" prob="40" />
		<npc_skill id="18164" lv="50" prob="20" />
		<npc_skill id="16608" lv="50" prob="10" />
	</npc_skills>
	<npc_skills npc_ids="219635"><!-- Laksyaka Magus -->
		<npc_skill id="18174" lv="50" prob="20" />
		<npc_skill id="16775" lv="50" prob="20" />
		<npc_skill id="17039" lv="50" prob="20" />
		<npc_skill id="16570" lv="50" prob="40" />
	</npc_skills>
	<npc_skills npc_ids="219637"><!-- Laksyaka Sniper -->
		<npc_skill id="18173" lv="50" prob="30" />
		<npc_skill id="16812" lv="50" prob="26" />
		<npc_skill id="16815" lv="50" prob="9" />
		<npc_skill id="17003" lv="50" prob="17" />
		<npc_skill id="16674" lv="50" prob="9" />
		<npc_skill id="18178" lv="50" prob="4" />
		<npc_skill id="16543" lv="50" prob="4" />
	</npc_skills>
	<npc_skills npc_ids="219638"><!-- Laksyaka Officer -->
		<npc_skill id="17008" lv="50" prob="21" />
		<npc_skill id="16566" lv="50" prob="25" />
		<npc_skill id="16563" lv="50" prob="32" />
		<npc_skill id="16638" lv="50" prob="14" />
		<npc_skill id="16565" lv="50" prob="4" />
		<npc_skill id="16837" lv="50" prob="4" />
	</npc_skills>
</npc_skill_templates>
